drop table if exists Translation CASCADE;
create table Translation
(
    id           bigint generated by default as identity,
    appId        varchar(255),
    context      varchar(255),
    textId       varchar(255),
    stage        varchar(255),
    de           varchar(255),
    fr           varchar(255),
    it           varchar(255),
    en           varchar(255),
    lastCall     date,
    isTranslated boolean not null,
    primary key (id)
);
alter table Translation
    add constraint UK8x7aoky72tpp9es47dgcwjctc unique (textId, appId, stage);

INSERT INTO TRANSLATION (TEXTID, APPID, CONTEXT, STAGE, DE, FR, IT, EN, LASTCALL, ISTRANSLATED)
VALUES ('test.sample.any.component.title', 'OPC', 'Dialog', 'DEV-Default', null, null, null,
        null, null, false),
       ('test.sample.any.component.firstname', 'COB', 'Login', 'ACC-Default', 'Vorname', 'Prénom', 'nome di battesimo',
        'firstname', CURRENT_TIMESTAMP(), true),
       ('test.sample.any.component.firstname', 'COB', 'Login', 'DEV-Default', 'Vorname', 'Prénom', 'nome di battesimo',
        'firstname', CURRENT_TIMESTAMP() - 10, true),
       ('test.sample.any.component.firstname', 'COB', 'Login', 'PROD', 'Vorname', 'Prénom', 'nome di battesimo',
        'firstname', CURRENT_TIMESTAMP() - 50, true),
       ('test.sample.any.component.lastname', 'UWD', 'Login', 'DEV-Integration', 'Nachname', 'Nom de famille',
        'Cognome',
        'Lastname', CURRENT_TIMESTAMP() - 5, true);